[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[scheduled]]
  path = "/.netlify/functions/daily"
  schedule = "0 13 * * *"
